<?php

/**
 * Created by PhpStorm.
 * User: nguyenthanh
 * Date: 8/6/16
 * Time: 10:59
 */
include "database.php";
class user extends database
{
    private $table = 'user';

    public function __construct()
    {
        parent::__construct();
    }
    public function getItemById($id)
    {
        return parent::getItemById($this->table,$id); // TODO: Change the autogenerated stub
    }

    //override
    public function getAll($table)
    {
        return parent::getAll($this->table); // TODO: Change the autogenerated stub
    }



}
